schema_version: 1

context:
  version: "1.0.3"

package:
  name: ansible-aap-api-client
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/ansible-aap-api-client/ansible_aap_api_client-${{ version }}.tar.gz
  sha256: 6b1cf71588e60a0743dd7c0fb2e24c27c4c1d1aa18e055fff0c99f354304d786

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=67.6.0
  run:
    - python >=${{ python_min }}
    - niquests >=3.18.6
    - urllib3 >=2.7.0

tests:
  - python:
      imports:
        - ansible_aap_api_client
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true

about:
  summary: |
    A client to interact with Ansible AAP REST API
  homepage: https://github.com/btr1975/ansible-aap-api-client
  repository: https://github.com/btr1975/ansible-aap-api-client
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - killua156
    - mgorny
